### ISSUE TITLE
Current Status of this project?

### ISSUE THREAD

**Issue by moogle19** [elixir-ecto/tds#128]
@aknazhansk Is this project still maintained?

It seems that the old maintainer doesn't work at @livehelpnow anymore and the repo didn't get much attention since.
Would it maybe be possible to transfer it (to @elixir-ecto for example) to at least get some PRs merged?

**Comment by aknazhansk** [comment]
@ewitchin Does what Kevin say makes sense here?

**Comment by ewitchin** [comment]
If the members of @elixir-ecto would like to take over tds and tds_ecto repos we can transfer them over.

**Comment by josevalim** [comment]
@ewitchin thanks, done! :heart:

@mjaric can you please add me to Hex? `mix hex.owner add tds josevalim`.

**Comment by josevalim** [comment]
If anyone is interested in becoming active in the project and help maintain it, please let me know here.

**Comment by moogle19** [comment]
@mjaric Thanks for adding to the `tds_encoding` repo. Could you also make me an owner in hex so I can make a new release?

**Comment by mjaric** [comment]
I will later today

**Comment by moogle19** [comment]
@josevalim 
I just released a new version (`2.2.0`).
When I wanted to update it in one of my projects, I noticed that `ecto_sql` has the `tds` version pinned to `2.1.x`.
Would it be reasonable to change it to `~> 2.1`?
