### ISSUE TITLE
Pull ntlm_auth to master

### ISSUE THREAD

**Issue by pulzzedavid** [elixir-ecto/tds#130]
We have a need to support TLS connection to MS SQL, and looks like basic connectivity works with the TLS work done on ntlm_auth branch. Is there any plan to pull that branch into master?

**Comment by moogle19** [comment]
@pulzzedavid 
I just released version `2.3.0-rc.0`. I ran the `ssl` branch for like the past month on an internal project of ours without problems.
But it would be nice if you could also test it and give me some feedback if something doesn't work as expected.
