### ISSUE TITLE
Casting to nvarchar(max) returns nil results.

### ISSUE THREAD

**Issue by CaldwellYSR** [elixir-ecto/tds#135]
### Environment

* Elixir version (elixir -v): 1.12.3
* Database and version (PostgreSQL 9.4, MongoDB 3.2, etc.): mcr.microsoft.com/mssql/server:2017-latest-ubuntu
* Ecto version (mix deps): 
* Database adapter and version (mix deps):
      ```
      {:ecto_sql, "~> 3.4"},
      {:tds, "~> 2.2"},
      {:tds_encoding, "~> 1.1"},
      ```
* Operating system: elixir:1.12.3 Dockerfile

### Current behavior
We have a very large query that is building a sentence. The sentence being built is a `varchar(499)` which causes `nil` results to be returned. When attempting to cast to `nvarchar(max)` the same nil results are returned.

We ended up storing the casted output of the query into a table that explicitly defines the `top_pick_sentence` as `nvarchar(max)` then we are able to successfully query that table for the data.

```
query = "select cast(top_pick_sentence as nvarchar(max)) as top_pick_sentence from ..."
MyApp.Repo.query(query, [])

# {:ok, %Tds.Result{columns: nil, num_rows: 1, rows: nil}}
```

### Expected behavior
Casting a `varchar(499)` to `nvarchar(max)` should work just the same as casting and then storing the data to be retrieved later.

**Comment by moogle19** [comment]
Hi @CaldwellYSR ,
I tried to reproduce your problem, but in my example it seems to work.

I tried the following:

```elxir
iex> Repo.query("CREATE TABLE varchar_test (top_pick_sentence varchar(499))")
{:ok, %Tds.Result{columns: nil, num_rows: 0, rows: nil}}

iex> Repo.query("INSERT INTO varchar_test VALUES ('some veeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyy long string')")
{:ok, %Tds.Result{columns: nil, num_rows: 1, rows: nil}}

iex> Repo.query("select cast(top_pick_sentence as nvarchar(max)) as top_pick_sentence from varchar_test", [])
{:ok,
 %Tds.Result{
   columns: ["top_pick_sentence"],
   num_rows: 1,
   rows: [
     ["some veeeeeeeeeeeeeeeeeeeeeeeeerrrrrrrrrrrrrrrrrrryyyyyyyyyyyyyyyyyyyyy long string"]
   ]
 }}
```

Could you try the example above in your environment and maybe enable debug output for the queries, which are problematic, so I can take a look at the raw SQL queries?

**Comment by CaldwellYSR** [comment]
Sorry, I was going back and forth with the guy the wrote the SQL in question and I think we were wrong about the problem. We tested with another couple queries that had similar casting but they didn't give the same issue. We are thinking the issue might be coming from something weird he is doing with the date variable that's being passed into the query. Unfortunately the query is 1500+ lines long so debugging it is a bit outside my scope.

I will get back to you if we get anywhere with it.

**Comment by CaldwellYSR** [comment]
@moogle19 I guess I'm going to close this issue because it's clearly incorrect. The SQL guy has given me a new query that works even when casting to nvarchar so clearly the casting isn't the issue. He believes the issue was related to that query using a ton of unions but he doesn't know that for sure.

If we find out what broke it I will create another issue.
