### ISSUE TITLE
TDS and query prefixes to access several databases inside MSSQL

### ISSUE THREAD

**Issue by miguelvillaresb** [elixir-ecto/tds#158]
### Environment

* Elixir version (elixir -v): Elixir 1.14.5 (compiled with Erlang/OTP 25)
* TDS version (mix deps): 2.3
* MSSQL Server version (SQL Server 2016 / 2019 / Azure SQL Edge): Microsoft SQL Server 2012 (SP4) (KB4018073) 
* Additional configuration parameter (`ssl_opts`, `socket_options`, ...): 
```
   ssl: :required,
   ssl_opts: [verify: :verify_none]
```
* Operating system: MacOS

### Expected behavior
Trying to access several MSSQL databases I am using query prefixes but I am not getting results. I mean, this code is working fine and I get results:
```
      sql_query = """
      SELECT c.snombrecli FROM "14637_advAboUsu1".dbo.clientes AS c WHERE c.icodcli = 1;
      """

      {:ok, result} = MNRepo.query(sql_query, [])
```

But I am trying to use query prefix in the following way and I am getting an error, object '14637_advAboUsu1.dbo.clientes' is not valid.
```
      query =
        from(c in "clientes",
          where: c.icodcli == 1,
          select: c.snombrecli
        )

      results =
        query
        |> Ecto.Query.put_query_prefix("14637_advAboUsu1.dbo")
        |> MNRepo.all()

```
I would expect same result for both of them.

### Actual behavior
Second option using Ecto query raises an error.

**Comment by mjaric** [comment]
This is rather ecto_sql issue (limitation), can you open it there please?
